export class RegexStrings {
    // The marker has to BEGIN with TOC. Matching "TOC" anywhere inside any HTML
    // comment made an ordinary attribution comment such as
    // "<!-- Generated by auto-markdown-toc -->" register as the start of the TOC
    // block, so everything between it and <!-- /TOC --> was replaced on the next
    // update. The \b keeps <!-- TOCX --> from matching.
    readonly REGEXP_TOC_START = /^\s*<!--\s*TOC\b(.*?)-->/i;
    readonly REGEXP_TOC_STOP = /^\s*<!--\s*\/TOC\b(.*?)-->/i;
    readonly REGEXP_TOC_CONFIG = /\w+[:=][^\s]+/gi;
    readonly REGEXP_TOC_CONFIG_ITEM = /(\w+)[:=]([^\s]+)/;
    readonly REGEXP_MARKDOWN_ANCHOR = /^<a id="markdown-.+" name=".+"><\/a\>/;
    readonly REGEXP_CODE_BLOCK1 = /^\s?```/;
    readonly REGEXP_CODE_BLOCK2 = /^\s?~~~/;
    readonly REGEXP_ANCHOR = /\[.+\]\(#(.+)\)/;
    // "ingore" is the original typo. Documents in the wild use it, so both
    // spellings have to keep working.
    readonly REGEXP_IGNORE_TITLE = /<!--\s*TOC\s+i(?:gn|ng)ore:true\s*-->/si;

    // Groups: 1 = header marks, 2 = section number (undefined when absent),
    // 3 = title.
    //
    // A section number is a run of digits and dots that is SEPARATED FROM THE
    // TITLE BY WHITESPACE: "1.", "1.1", "2.3.4." all qualify in "## 1.1. Title".
    // That separator is what keeps a bare version heading such as "# 1.1.1" a
    // title. The previous pattern had no such requirement, so it split
    // "# 1.1.1" into the number "1.1." and the title "1" — which, once header
    // renumbering became the default, rewrote CHANGELOG version headings in
    // place.
    readonly REGEXP_HEADER_META = /^(#*)\s*(?:((?:\d+\.)+\d*|\d+\.)\s+)?(.+)$/;
    readonly REGEXP_UNIQUE_CONFIG_START = /\s*<!--(.*)[^\/]TOC UNIQUE CONFIGS(.*)-->/gi;
    readonly REGEXP_UNIQUE_CONFIG_STOP = /\s*<!--(.*)\/TOC UNIQUE CONFIGS(.*)-->/gi;
    readonly REGEXP_UNIQUE_CONFIG_LINE = /\s*<!--( *)(\w+)[:](\w+)( *)-->/gi;

    private static _instance: RegexStrings;

    private constructor() { }

    public static get Instance() {
        return this._instance || (this._instance = new this());
    }
}